server:
  port: 9702

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8700}/eureka/
    healthcheck:
      enable: true
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/cgpt?autoReconnect=true&useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    application:
        name: service

# mybatis配置
# mapper-locations 扫描 *Mapper.xml的路径，多个时用" ，"隔开
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.tor.project.*

logging:
  level:
    com.tor: debug