server:
  port: 8548

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/aiqinhai?autoReconnect=true&useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    mvc:
        view:
          prefix: /
          suffix: .html
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      mode: HTML5
      servlet:
        content-type: text/html
    application:
        name: project-aqhcoms

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml,com/tor/*/mapper/xml/*Mapper.xml
  type-aliases-package: com.tor.project.*

#eureka:
#  client:
#    service-url:
#      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8700}/eureka/
#    healthcheck:
#      enable: true
#  instance:
#    hostname: ${spring.cloud.client.ipAddress}
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    prefer-ip-address: true
#    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号

logging:
  level:
    com.tor: debug

