banner:
  location: config/banner.txt
  encoding: utf-8

server:
  port: 8548
  context-path: /
  session:
    timeout: 1800
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://120.78.154.0:3306/aiqinhai?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .html
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    content-type: text/html
  application:
    name: project-aqhcoms
  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml,com/tor/*/mapper/xml/*Mapper.xml
  type-aliases-package: com.tor.*.*

#eureka:
#  client:
#    service-url:
#      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8700}/eureka/
#    healthcheck:
#      enable: true
#  instance:
#    hostname: ${spring.cloud.client.ipAddress}
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    prefer-ip-address: true
#    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号

logging:
  level:
    com.tor: debug

