server:
  port: 3537

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/cgpt?autoReconnect=true&useUnicode=true&characterEncoding=utf8
        username: ${DATABASE_USER_NAME}
        password: ${DATABASE_PASSWORD}
        driver-class-name: com.mysql.jdbc.Driver
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.tor

logging:
  level:
    com.tor: debug