regVer: QingHai
spring:
  datasource:
    druid:
      # （主）医保监管数据源
      primary:
        driver-class-name: oracle.jdbc.OracleDriver
        jdbc-url: jdbc:oracle:thin:@10.130.131.236:1521:ORCL
        username: spzpjkdb
        password: hzhl#zjut5607
      # （从）如果不需要配置双数据源,配置跟主数据源一致即可
#      second:
#        driver-class-name: com.mysql.jdbc.Driver
#        jdbc-url: jdbc:mysql://47.103.194.192:3306/ifast-new2?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true
#        username: root
#        password: root
      # （从）如果不需要配置双数据源,配置跟主数据源一致即可
      second:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://10.130.131.236:3306/yhbiology?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true
        username: yhbiology
        password: hzhl#zjut5607

# 定时任务
# 0 0 1 * * ?
# 0 0 0/2 * * ?
# 0 */5 * * * ?
# 0/60 * * * * ?
JyJob:
  JyInfoJob: 0 0 0/2 * * ?
  JyPhotosJob: 0 0 1 * * ?
HyJob:
  HyInfoAndPhotosJob: 0 0 1 * * ?
QhJob:
  QhInfoJob: 0 0 0/2 * * ?
  QhPhotosJob: 0 0 1 * * ?

# 单次处理最大数量
handle_max_size: 100
# 金华照片物理地址根目录
migrate_jzpp_photo_path: C:\Users\Administrator\Pictures\